import SwiftUI

enum Themes {
  static let defaultLightID = "tokyo-day"
  static let defaultDarkID = "catppuccin-mocha"

  // MARK: - Dark themes

  static let dark: [Theme] = [
    Theme(
      id: "tokyo-night",
      name: "Tokyo Night",
      isDark: true,
      background: Color(hex: "1a1b26"),
      surface: Color(hex: "24283b"),
      elevated: Color(hex: "292e42"),
      textPrimary: Color(hex: "c0caf5"),
      textSecondary: Color(hex: "565f89"),
      separator: Color(hex: "2f3549"),
      accent: Color(hex: "7aa2f7"),
      accent2: Color(hex: "bb9af7"),
      success: Color(hex: "9ece6a"),
      warning: Color(hex: "e0af68"),
      error: Color(hex: "f7768e"),
      info: Color(hex: "7dcfff")
    ),
    Theme(
      id: "catppuccin-mocha",
      name: "Catppuccin Mocha",
      isDark: true,
      background: Color(hex: "1e1e2e"),
      surface: Color(hex: "313244"),
      elevated: Color(hex: "45475a"),
      textPrimary: Color(hex: "cdd6f4"),
      textSecondary: Color(hex: "a6adc8"),
      separator: Color(hex: "45475a"),
      accent: Color(hex: "89b4fa"),
      accent2: Color(hex: "cba6f7"),
      success: Color(hex: "a6e3a1"),
      warning: Color(hex: "fab387"),
      error: Color(hex: "f38ba8"),
      info: Color(hex: "89dceb")
    ),
    Theme(
      id: "dracula",
      name: "Dracula",
      isDark: true,
      background: Color(hex: "282a36"),
      surface: Color(hex: "343746"),
      elevated: Color(hex: "44475a"),
      textPrimary: Color(hex: "f8f8f2"),
      textSecondary: Color(hex: "6272a4"),
      separator: Color(hex: "44475a"),
      accent: Color(hex: "bd93f9"),
      accent2: Color(hex: "ff79c6"),
      success: Color(hex: "50fa7b"),
      warning: Color(hex: "ffb86c"),
      error: Color(hex: "ff5555"),
      info: Color(hex: "8be9fd")
    ),
    Theme(
      id: "nord",
      name: "Nord",
      isDark: true,
      background: Color(hex: "2e3440"),
      surface: Color(hex: "3b4252"),
      elevated: Color(hex: "434c5e"),
      textPrimary: Color(hex: "eceff4"),
      textSecondary: Color(hex: "8f9ab0"),
      separator: Color(hex: "434c5e"),
      accent: Color(hex: "88c0d0"),
      accent2: Color(hex: "81a1c1"),
      success: Color(hex: "a3be8c"),
      warning: Color(hex: "ebcb8b"),
      error: Color(hex: "bf616a"),
      info: Color(hex: "5e81ac")
    ),
    Theme(
      id: "gruvbox-dark",
      name: "Gruvbox Dark",
      isDark: true,
      background: Color(hex: "282828"),
      surface: Color(hex: "3c3836"),
      elevated: Color(hex: "504945"),
      textPrimary: Color(hex: "ebdbb2"),
      textSecondary: Color(hex: "a89984"),
      separator: Color(hex: "3c3836"),
      accent: Color(hex: "fe8019"),
      accent2: Color(hex: "8ec07c"),
      success: Color(hex: "b8bb26"),
      warning: Color(hex: "fabd2f"),
      error: Color(hex: "fb4934"),
      info: Color(hex: "83a598")
    ),
    Theme(
      id: "rose-pine",
      name: "Rosé Pine",
      isDark: true,
      background: Color(hex: "191724"),
      surface: Color(hex: "1f1d2e"),
      elevated: Color(hex: "26233a"),
      textPrimary: Color(hex: "e0def4"),
      textSecondary: Color(hex: "908caa"),
      separator: Color(hex: "26233a"),
      accent: Color(hex: "c4a7e7"),
      accent2: Color(hex: "ebbcba"),
      success: Color(hex: "9ccfd8"),
      warning: Color(hex: "f6c177"),
      error: Color(hex: "eb6f92"),
      info: Color(hex: "31748f")
    ),
    Theme(
      id: "one-dark",
      name: "One Dark",
      isDark: true,
      background: Color(hex: "282c34"),
      surface: Color(hex: "2c313a"),
      elevated: Color(hex: "3b4048"),
      textPrimary: Color(hex: "abb2bf"),
      textSecondary: Color(hex: "828997"),
      separator: Color(hex: "3b4048"),
      accent: Color(hex: "61afef"),
      accent2: Color(hex: "c678dd"),
      success: Color(hex: "98c379"),
      warning: Color(hex: "e5c07b"),
      error: Color(hex: "e06c75"),
      info: Color(hex: "56b6c2")
    ),
    Theme(
      id: "monokai-pro",
      name: "Monokai Pro",
      isDark: true,
      background: Color(hex: "2d2a2e"),
      surface: Color(hex: "363438"),
      elevated: Color(hex: "403e41"),
      textPrimary: Color(hex: "fcfcfa"),
      textSecondary: Color(hex: "939293"),
      separator: Color(hex: "403e41"),
      accent: Color(hex: "78dce8"),
      accent2: Color(hex: "ab9df2"),
      success: Color(hex: "a9dc76"),
      warning: Color(hex: "ffd866"),
      error: Color(hex: "ff6188"),
      info: Color(hex: "fc9867")
    ),
    Theme(
      id: "solarized-dark",
      name: "Solarized Dark",
      isDark: true,
      background: Color(hex: "002b36"),
      surface: Color(hex: "073642"),
      elevated: Color(hex: "0d4a58"),
      textPrimary: Color(hex: "93a1a1"),
      textSecondary: Color(hex: "657b83"),
      separator: Color(hex: "0d4a58"),
      accent: Color(hex: "268bd2"),
      accent2: Color(hex: "6c71c4"),
      success: Color(hex: "859900"),
      warning: Color(hex: "b58900"),
      error: Color(hex: "dc322f"),
      info: Color(hex: "2aa198")
    ),
    Theme(
      id: "ayu-dark",
      name: "Ayu Dark",
      isDark: true,
      background: Color(hex: "0b0e14"),
      surface: Color(hex: "11151c"),
      elevated: Color(hex: "1c212b"),
      textPrimary: Color(hex: "bfbdb6"),
      textSecondary: Color(hex: "565b66"),
      separator: Color(hex: "1c212b"),
      accent: Color(hex: "ffb454"),
      accent2: Color(hex: "59c2ff"),
      success: Color(hex: "7fd962"),
      warning: Color(hex: "f29e74"),
      error: Color(hex: "f26d78"),
      info: Color(hex: "73b8ff")
    ),
  ]

  // MARK: - Light themes

  static let light: [Theme] = [
    Theme(
      id: "catppuccin-latte",
      name: "Catppuccin Latte",
      isDark: false,
      background: Color(hex: "eff1f5"),
      surface: Color(hex: "e6e9ef"),
      elevated: Color(hex: "dce0e8"),
      textPrimary: Color(hex: "4c4f69"),
      textSecondary: Color(hex: "6c6f85"),
      separator: Color(hex: "ccd0da"),
      accent: Color(hex: "1e66f5"),
      accent2: Color(hex: "8839ef"),
      success: Color(hex: "40a02b"),
      warning: Color(hex: "fe640b"),
      error: Color(hex: "d20f39"),
      info: Color(hex: "209fb5")
    ),
    Theme(
      id: "rose-pine-dawn",
      name: "Rosé Pine Dawn",
      isDark: false,
      background: Color(hex: "faf4ed"),
      surface: Color(hex: "fffaf3"),
      elevated: Color(hex: "f2e9e1"),
      textPrimary: Color(hex: "575279"),
      textSecondary: Color(hex: "797593"),
      separator: Color(hex: "dfdad9"),
      accent: Color(hex: "907aa9"),
      accent2: Color(hex: "d7827e"),
      success: Color(hex: "56949f"),
      warning: Color(hex: "ea9d34"),
      error: Color(hex: "b4637a"),
      info: Color(hex: "286983")
    ),
    Theme(
      id: "tokyo-day",
      name: "Tokyo Day",
      isDark: false,
      background: Color(hex: "e1e2e7"),
      surface: Color(hex: "d5d6db"),
      elevated: Color(hex: "c8cad3"),
      textPrimary: Color(hex: "3760bf"),
      textSecondary: Color(hex: "6172b0"),
      separator: Color(hex: "c4c8da"),
      accent: Color(hex: "2e7de9"),
      accent2: Color(hex: "9854f1"),
      success: Color(hex: "587539"),
      warning: Color(hex: "8c6c3e"),
      error: Color(hex: "f52a65"),
      info: Color(hex: "007197")
    ),
    Theme(
      id: "nord-light",
      name: "Nord Light",
      isDark: false,
      background: Color(hex: "eceff4"),
      surface: Color(hex: "e5e9f0"),
      elevated: Color(hex: "d8dee9"),
      textPrimary: Color(hex: "2e3440"),
      textSecondary: Color(hex: "4c566a"),
      separator: Color(hex: "d8dee9"),
      accent: Color(hex: "5e81ac"),
      accent2: Color(hex: "81a1c1"),
      success: Color(hex: "a3be8c"),
      warning: Color(hex: "ebcb8b"),
      error: Color(hex: "bf616a"),
      info: Color(hex: "88c0d0")
    ),
    Theme(
      id: "solarized-light",
      name: "Solarized Light",
      isDark: false,
      background: Color(hex: "fdf6e3"),
      surface: Color(hex: "eee8d5"),
      elevated: Color(hex: "e4ddc8"),
      textPrimary: Color(hex: "586e75"),
      textSecondary: Color(hex: "657b83"),
      separator: Color(hex: "ded8c4"),
      accent: Color(hex: "268bd2"),
      accent2: Color(hex: "6c71c4"),
      success: Color(hex: "859900"),
      warning: Color(hex: "b58900"),
      error: Color(hex: "dc322f"),
      info: Color(hex: "2aa198")
    ),
    Theme(
      id: "gruvbox-light",
      name: "Gruvbox Light",
      isDark: false,
      background: Color(hex: "fbf1c7"),
      surface: Color(hex: "ebdbb2"),
      elevated: Color(hex: "d5c4a1"),
      textPrimary: Color(hex: "3c3836"),
      textSecondary: Color(hex: "7c6f64"),
      separator: Color(hex: "d5c4a1"),
      accent: Color(hex: "d65d0e"),
      accent2: Color(hex: "427b58"),
      success: Color(hex: "79740e"),
      warning: Color(hex: "b57614"),
      error: Color(hex: "cc241d"),
      info: Color(hex: "076678")
    ),
    Theme(
      id: "one-light",
      name: "One Light",
      isDark: false,
      background: Color(hex: "fafafa"),
      surface: Color(hex: "eaeaeb"),
      elevated: Color(hex: "e5e5e6"),
      textPrimary: Color(hex: "383a42"),
      textSecondary: Color(hex: "696c77"),
      separator: Color(hex: "dcdcdd"),
      accent: Color(hex: "4078f2"),
      accent2: Color(hex: "a626a4"),
      success: Color(hex: "50a14f"),
      warning: Color(hex: "c18401"),
      error: Color(hex: "e45649"),
      info: Color(hex: "0184bc")
    ),
    Theme(
      id: "github-light",
      name: "GitHub Light",
      isDark: false,
      background: Color(hex: "ffffff"),
      surface: Color(hex: "f6f8fa"),
      elevated: Color(hex: "eaeef2"),
      textPrimary: Color(hex: "1f2328"),
      textSecondary: Color(hex: "656d76"),
      separator: Color(hex: "d0d7de"),
      accent: Color(hex: "0969da"),
      accent2: Color(hex: "8250df"),
      success: Color(hex: "1a7f37"),
      warning: Color(hex: "bc4c00"),
      error: Color(hex: "cf222e"),
      info: Color(hex: "0550ae")
    ),
    Theme(
      id: "everforest-light",
      name: "Everforest Light",
      isDark: false,
      background: Color(hex: "fdf6e3"),
      surface: Color(hex: "f4f0d9"),
      elevated: Color(hex: "efebd4"),
      textPrimary: Color(hex: "5c6a72"),
      textSecondary: Color(hex: "829181"),
      separator: Color(hex: "e0dcc7"),
      accent: Color(hex: "8da101"),
      accent2: Color(hex: "3a94c5"),
      success: Color(hex: "35a77c"),
      warning: Color(hex: "dfa000"),
      error: Color(hex: "f85552"),
      info: Color(hex: "3a94c5")
    ),
    Theme(
      id: "ios-sky",
      name: "iOS Sky",
      isDark: false,
      background: Color(hex: "f2f2f7"),
      surface: Color(hex: "ffffff"),
      elevated: Color(hex: "ffffff"),
      textPrimary: Color(hex: "1c1c1e"),
      textSecondary: Color(hex: "8e8e93"),
      separator: Color(hex: "c6c6c8"),
      accent: Color(hex: "007aff"),
      accent2: Color(hex: "5856d6"),
      success: Color(hex: "34c759"),
      warning: Color(hex: "ff9500"),
      error: Color(hex: "ff3b30"),
      info: Color(hex: "30b0c7")
    ),
  ]

  // MARK: - Lookup

  static let all: [Theme] = dark + light

  static func theme(id: String) -> Theme? {
    all.first { $0.id == id }
  }
}
